name: vcode
channels:
  - pytorch
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - nvidia
  - defaults
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.10
  - aiosignal=1.3.1
  - aom=3.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=13.0.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attr=2.5.2
  - attrs=24.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - boost-cpp=1.82.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.2
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cpython=3.12.12
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.68
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - cycler=0.11.0
  - datasets=2.19.2
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - executing=0.8.3
  - expat=2.7.1
  - ffmpeg=4.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.14.1
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - git=2.51.2
  - glib=2.86.0
  - glib-tools=2.86.0
  - glog=0.7.1
  - gmp=6.2.1
  - gnutls=3.7.9
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - huggingface_hub=1.0.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2025.0.0
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libarrow=13.0.0
  - libboost=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.68
  - libcurl=8.16.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libdrm=2.4.125
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.86.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgpg-error=1.55
  - libgrpc=1.62.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnl=3.11.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=12.20
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libudev1=257.4
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.21.0
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - mysql=5.7.20
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numpy-base=1.26.4
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.5.4
  - orc=2.0.1
  - overrides=7.4.0
  - p11-kit=0.24.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.46
  - perl=5.32.1
  - pexpect=4.8.0
  - pillow=11.0.0
  - pip=24.2
  - ply=3.11
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.2.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow-hotfix=0.7
  - pybind11-abi=5
  - pycparser=2.21
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-gil=3.12.12
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - rdma-core=55.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.9.11
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - s2n=1.4.17
  - send2trash=1.8.2
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - soupsieve=2.5
  - sqlite=3.50.4
  - stack_data=0.2.0
  - svt-av1=1.4.1
  - sympy=1.13.2
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - traitlets=5.14.3
  - typer-slim=0.20.0
  - tzdata=2024a
  - ucx=1.16.0
  - unicodedata2=15.1.0
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - widgetsnbextension=4.0.10
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.16.0
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.11.0
      - adagio==0.2.6
      - addict==2.4.0
      - alembic==1.14.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - appdirs==1.4.4
      - astunparse==1.6.3
      - av==14.3.0
      - blobfile==3.1.0
      - cachetools==5.5.0
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - click==8.1.7
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - coreforecast==0.0.15
      - cramjam==2.11.0
      - crcmod==1.7
      - cryptography==45.0.5
      - cssselect2==0.8.0
      - datasetsforecast==0.0.8
      - debugpy==1.8.17
      - dgl==2.4.0+cu121
      - diffusers==0.33.1
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - fastdtw==0.3.4
      - fastparquet==2024.11.0
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - fs==2.4.16
      - fugue==0.9.1
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - greenlet==3.1.1
      - grpcio==1.68.0
      - h5py==3.12.1
      - hf-xet==1.1.5
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.34.4
      - importlib-metadata==8.6.1
      - ipykernel==7.0.1
      - jiter==0.6.1
      - jmespath==0.10.0
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - keras==3.7.0
      - libclang==18.1.1
      - lightning-utilities==0.11.9
      - littleutils==0.2.4
      - llvmlite==0.43.0
      - loguru==0.7.2
      - lxml==6.0.1
      - mako==1.3.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mmengine==0.10.7
      - modelscope==1.25.0
      - msgpack==1.1.0
      - namex==0.0.8
      - networkx==2.8
      - neuralforecast==1.7.6
      - nltk==3.2.4
      - numba==0.60.0
      - numpy==2.3.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.4.1
      - ogb==1.3.6
      - openai==1.109.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.13.1
      - optuna==4.1.0
      - oss2==2.17.0
      - outcome==1.3.0.post0
      - outdated==0.2.2
      - packaging==25.0
      - pandas==2.3.1
      - patool==4.0.0
      - patsy==1.0.1
      - peft==0.15.2
      - platformdirs==4.3.6
      - playwright==1.55.0
      - preprocessing==0.1.13
      - prettytable==3.14.0
      - protobuf==5.29.0
      - psutil==6.1.0
      - pyarrow==21.0.0
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyecharts==2.0.8
      - pyee==13.0.0
      - pygments==2.18.0
      - pyjwt==2.8.0
      - python-dotenv==1.1.1
      - pytorch-lightning==2.4.0
      - pytz==2023.4
      - pywavelets==1.8.0
      - qwen-vl-utils==0.0.11
      - ray==2.40.0
      - redis==5.2.0
      - requests==2.32.5
      - rich==13.4.2
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.15.2
      - selenium==4.37.0
      - sentence-transformers==3.2.1
      - sentencepiece==0.2.1
      - sentry-sdk==2.19.0
      - setproctitle==1.3.4
      - setuptools==80.9.0
      - simplejson==3.20.1
      - simplification==0.7.13
      - smmap==5.0.1
      - snapshot-phantomjs==0.0.3
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sphinx-rtd-theme==0.2.4
      - sqlalchemy==2.0.36
      - statsmodels==0.14.4
      - stumpy==1.13.0
      - tabulate==0.9.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.9.0
      - timm==1.0.17
      - tokenizers==0.22.1
      - torch==2.4.0
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torchinfo==1.8.0
      - torchmetrics==1.6.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - triad==0.9.8
      - trio==0.31.0
      - trio-websocket==0.12.2
      - tsfresh==0.21.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - utilsforecast==0.2.10
      - volcengine-python-sdk==4.0.7
      - wandb==0.18.7
      - webdriver-manager==4.0.2
      - werkzeug==3.1.3
      - wheel==0.45.1
      - wrapt==1.17.0
      - wsproto==1.2.0
      - xlrd==2.0.1
      - yapf==0.43.0
      - zai-sdk==0.0.3.1
      - zhipuai==2.1.5.20250825
      - zipp==3.21.0
